# Generated by Django 3.0.5 on 2020-10-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0002_auto_20201014_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_no',
            field=models.BigIntegerField(),
        ),
    ]
